"""
This type stub file was generated by pyright.
"""

from contextlib import contextmanager
from typing import List, Optional, Any, Dict, Union, Generator, Callable
from PIL import Image
import subprocess

tesseract_cmd = ...
numpy_installed = ...
pandas_installed = ...
LOGGER = ...
DEFAULT_ENCODING = ...
LANG_PATTERN = ...
RGB_MODE = ...
SUPPORTED_FORMATS = ...
OSD_KEYS = ...
EXTENTION_TO_CONFIG = ...
TESSERACT_MIN_VERSION = ...
TESSERACT_ALTO_VERSION = ...
class Output:
    BYTES = ...
    DATAFRAME = ...
    DICT = ...
    STRING = ...


class PandasNotSupported(EnvironmentError):
    def __init__(self) -> None:
        ...
    


class TesseractError(RuntimeError):
    def __init__(self, status: int, message: str) -> None:
        ...
    


class TesseractNotFoundError(EnvironmentError):
    def __init__(self) -> None:
        ...
    


class TSVNotSupported(EnvironmentError):
    def __init__(self) -> None:
        ...
    


class ALTONotSupported(EnvironmentError):
    def __init__(self) -> None:
        ...
    


def kill(process: subprocess.Popen[bytes], code: int) -> None:
    ...

@contextmanager
def timeout_manager(proc: subprocess.Popen[bytes], seconds: int = ...) -> Generator[Any, Any, None]:
    ...

def run_once(func: Callable[..., Any]) -> Callable[..., Any]:
    ...

def get_errors(error_string: str) -> str:
    ...

def cleanup(temp_name: str) -> None:
    """Tries to remove temp files by filename wildcard path."""
    ...

def prepare(image: Any) -> tuple[Image.Image, str]:
    ...

@contextmanager
def save(image: Any) -> Generator[tuple[str, str], Any, None]:
    ...

def subprocess_args(include_stdout: bool = ...) -> dict[str, Any]:
    ...

def run_tesseract(
    input_filename: str, 
    output_filename_base: str, 
    extension: str, 
    lang: Optional[str], 
    config: str = ..., 
    nice: int = ..., 
    timeout: int = ...
) -> None:
    ...

def run_and_get_multiple_output(
    image: Any, 
    extensions: List[str], 
    lang: Optional[str] = ..., 
    nice: int = ..., 
    timeout: int = ..., 
    return_bytes: bool = ...
) -> List[Union[bytes, str]]:
    ...

def run_and_get_output(
    image: Any, 
    extension: str = ..., 
    lang: Optional[str] = ..., 
    config: str = ..., 
    nice: int = ..., 
    timeout: int = ..., 
    return_bytes: bool = ...
) -> Union[bytes, str]:
    ...

def file_to_dict(tsv: str, cell_delimiter: str, str_col_idx: List[int]) -> Dict[str, List[Any]]:
    ...

def is_valid(val: Any, _type: type) -> bool:
    ...

def osd_to_dict(osd: str) -> Dict[str, Any]:
    ...

@run_once
def get_languages(config: str = ...) -> List[str]:
    ...

@run_once
def get_tesseract_version() -> Any:  # Version type not imported
    """
    Returns Version object of the Tesseract version
    """
    ...

def image_to_string(
    image: Any, 
    lang: Optional[str] = ..., 
    config: str = ..., 
    nice: int = ..., 
    output_type: Any = ..., 
    timeout: int = ...
) -> str:
    """
    Returns the result of a Tesseract OCR run on the provided image to string
    """
    ...

def image_to_pdf_or_hocr(
    image: Any, 
    lang: Optional[str] = ..., 
    config: str = ..., 
    nice: int = ..., 
    extension: str = ..., 
    timeout: int = ...
) -> Union[bytes, str]:
    """
    Returns the result of a Tesseract OCR run on the provided image to pdf/hocr
    """
    ...

def image_to_alto_xml(
    image: Any, 
    lang: Optional[str] = ..., 
    config: str = ..., 
    nice: int = ..., 
    timeout: int = ...
) -> Union[bytes, str]:
    """
    Returns the result of a Tesseract OCR run on the provided image to ALTO XML
    """
    ...

def image_to_boxes(
    image: Any, 
    lang: Optional[str] = ..., 
    config: str = ..., 
    nice: int = ..., 
    output_type: Any = ..., 
    timeout: int = ...
) -> str:
    """
    Returns string containing recognized characters and their box boundaries
    """
    ...

def get_pandas_output(args: List[str], config: Dict[str, Any] = ...) -> Any:
    ...

def image_to_data(
    image: Any, 
    lang: Optional[str] = ..., 
    config: str = ..., 
    nice: int = ..., 
    output_type: Any = ..., 
    timeout: int = ..., 
    pandas_config: Dict[str, Any] = ...
) -> Dict[str, List[Any]]:
    """
    Returns string containing box boundaries, confidences,
    and other information. Requires Tesseract 3.05+
    """
    ...

def image_to_osd(
    image: Any, 
    lang: Optional[str] = ..., 
    config: str = ..., 
    nice: int = ..., 
    output_type: Any = ..., 
    timeout: int = ...
) -> str:
    """
    Returns string containing the orientation and script detection (OSD)
    """
    ...

def main() -> Optional[int]:
    ...

if __name__ == '__main__':
    ...
